global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Database API Server
  - job_name: 'database-api'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Physics Agents API Server
  - job_name: 'physics-api'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'  
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Database
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
    scrape_interval: 30s

  # Neo4j Database
  - job_name: 'neo4j'
    static_configs:
      - targets: ['localhost:2004']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Redis Database
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']
    scrape_interval: 30s

  # Node Exporter for System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Streamlit UI Application  
  - job_name: 'streamlit-app'
    static_configs:
      - targets: ['localhost:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']