apiVersion: v1
kind: ConfigMap
metadata:
  name: physics-assistant-config
  namespace: physics-assistant
data:
  # API Configuration
  API_HOST: "0.0.0.0"
  DATABASE_API_PORT: "8001"
  DASHBOARD_API_PORT: "8002"
  PHYSICS_API_PORT: "8000"
  
  # Database Configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "physics_assistant"
  POSTGRES_USER: "physics_user"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  NEO4J_HOST: "neo4j-service"
  NEO4J_PORT: "7687"
  NEO4J_HTTP_PORT: "7474"
  NEO4J_USER: "neo4j"
  
  # Logging Configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # Analytics Configuration
  ML_MODEL_PATH: "/app/models"
  CELERY_WORKER_CONCURRENCY: "4"
  
  # Resource Limits
  MAX_UPLOAD_SIZE: "100MB"
  REQUEST_TIMEOUT: "300"
  WORKER_TIMEOUT: "600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: physics-assistant
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
          action: keep
          regex: default;kubernetes;https
      
      - job_name: 'physics-assistant-apis'
        kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - physics-assistant
        relabel_configs:
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_service_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_service_name]
          action: replace
          target_label: kubernetes_name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: physics-assistant
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-service:9090
      isDefault: true