apiVersion: v1
kind: Secret
metadata:
  name: physics-assistant-secrets
  namespace: physics-assistant
type: Opaque
data:
  # Base64 encoded secrets - these should be replaced with actual values
  # To encode: echo -n 'your-password' | base64
  
  # Database passwords
  postgres-password: c2VjdXJlX3Bvc3RncmVzX3Byb2RfMjAyNCE=  # secure_postgres_prod_2024!
  physics-db-password: c2VjdXJlX3BoeXNpY3NfZGJfcHJvZF8yMDI0IQ==  # secure_physics_db_prod_2024!
  monitor-db-password: c2VjdXJlX21vbml0b3JfZGJfcHJvZF8yMDI0IQ==  # secure_monitor_db_prod_2024!
  neo4j-password: c2VjdXJlX25lbzRqX3Byb2RfMjAyNCE=  # secure_neo4j_prod_2024!
  redis-password: c2VjdXJlX3JlZGlzX3Byb2RfMjAyNCE=  # secure_redis_prod_2024!
  
  # Application secrets
  secret-key: eW91ci1zdXBlci1zZWNyZXQta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=
  jwt-secret-key: eW91ci1qd3Qtc2VjcmV0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u
  csrf-secret-key: eW91ci1jc3JmLXNlY3JldC1rZXk=
  
  # Monitoring
  grafana-admin-password: c2VjdXJlX2dyYWZhbmFfYWRtaW5fMjAyNCE=  # secure_grafana_admin_2024!
  
  # External services
  smtp-password: eW91ci1zbXRwLXBhc3N3b3Jk  # your-smtp-password
---
apiVersion: v1
kind: Secret
metadata:
  name: container-registry-secret
  namespace: physics-assistant
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==