# Prometheus Configuration for Physics Assistant
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'physics-assistant'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/alert_rules.yml"

# Scrape configuration
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Database API monitoring
  - job_name: 'database-api'
    static_configs:
      - targets: ['database-api:8001']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Dashboard API monitoring
  - job_name: 'dashboard-api'
    static_configs:
      - targets: ['dashboard-api:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Physics Agents API monitoring
  - job_name: 'physics-agents-api'
    static_configs:
      - targets: ['physics-agents-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL monitoring
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Neo4j monitoring
  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # MCP servers monitoring
  - job_name: 'mcp-servers'
    static_configs:
      - targets: 
        - 'mcp-forces:10100'
        - 'mcp-kinematics:10100'
        - 'mcp-math:10100'
        - 'mcp-energy:10100'
        - 'mcp-momentum:10100'
        - 'mcp-angular-motion:10100'
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Alertmanager monitoring
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s