# Loki Configuration for Physics Assistant
# Centralized logging with performance optimization

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Frontend configuration
frontend:
  max_outstanding_per_tenant: 2048
  compress_responses: true

# Limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  max_query_parallelism: 32
  max_streams_per_user: 10000
  max_line_size: 256KB
  max_entries_limit_per_query: 5000
  max_chunks_per_query: 2000000
  max_query_series: 5000

# Compactor configuration
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

# Analytics configuration
analytics:
  reporting_enabled: false

# Performance tuning
chunk_store_config:
  max_look_back_period: 168h

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7 days

# Query frontend configuration
frontend_worker:
  frontend_address: 127.0.0.1:9095